Feat/google speech
coronasafe/ayushma pull request #116
Opened 2023-05-15 17:29 UTC by ishanExtreme

2023-05-15 18:23 UTC, skks1212 requested changes

2023-05-15 18:23 UTC, skks1212 commented on output.mp3
Was this committed by mistake?

2023-05-16 10:26 UTC, ishanExtreme commented on output.mp3
nopes, mistake

2023-05-16 12:19 UTC, skks1212 approved these changes

2023-05-16 12:20 UTC, merged